// GENERATED BY gg_version WriteVersionFile - DO NOT EDIT.
// Kept in sync by test/testproject_2_version.test.ts.

/** The version of the `@tssuite/testproject_2` package. */
export const testproject2Version = '0.1.6';
